// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PitochokPlague.Infrastructure;

#nullable disable

namespace PitochokPlague.Migrations
{
    [DbContext(typeof(PitochokPlagueContext))]
    [Migration("20231014202154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PitochokPlague.Infrastructure.Patients.PatientModel", b =>
                {
                    b.Property<int>("Isu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Isu"));

                    b.Property<int>("CarrierIsu")
                        .HasColumnType("integer")
                        .HasColumnName("carrier_isu");

                    b.Property<DateTime>("IncubationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incubation_time");

                    b.HasKey("Isu")
                        .HasName("pk_patients");

                    b.HasIndex("Isu")
                        .HasDatabaseName("ix_patients_isu");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("PitochokPlague.Infrastructure.Patients.ResistantModel", b =>
                {
                    b.Property<int>("Isu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("isu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Isu"));

                    b.Property<int>("ImmuneStatus")
                        .HasColumnType("integer")
                        .HasColumnName("immune_status");

                    b.HasKey("Isu")
                        .HasName("pk_resistants");

                    b.HasIndex("Isu")
                        .HasDatabaseName("ix_resistants_isu");

                    b.ToTable("resistants", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
